services:
  - type: web
    name: server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: "mongodb+srv://Mk50032266:Mk50032266@cluster0.izuvmy9.mongodb.net/test?retryWrites=true&w=majority"
